### ISSUE TITLE
Views for ADO Tools children

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment-live#109]
# What?
Corresponding issue for esmero/archipelago-deployment#247, esmero/strawberry_runners#62, and esmero/strawberryfield#237.

The same files from esmero/archipelago-deployment#248 will be copied here.

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/archipelago-deployment-live/commit/13038a7123a503715b2baa3426a9d2f7aa0e0b69
