### ISSUE TITLE
Self signed docker-composer was a wrong ENV variable set

### ISSUE THREAD

**Issue by DiegoPino** [esmero/archipelago-deployment-live#21]
# What?

Reported by @ksuquix

On line 100 we are setting the `Bucket name` instead of the Bucket prefix. We have not tested self signature in a long time mostly because Browsers are simply so bad and dealing with those and makes really testing a mess. But its needed.

Correct one is `S3SOURCE_BASICLOOKUPSTRATEGY_PATH_PREFIX: ${MINIO_FOLDER_PREFIX_MEDIA}`

See https://github.com/esmero/archipelago-deployment-live/pull/20

**Comment by ksuquix** [comment]
FYI, I started at this point mostly because I never intended to terminate SSL inside docker, and it seemed an easier starting point to rip out the SSL pieces.

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/archipelago-deployment-live/commit/6fda43e4e8b1e78b24f1ffaac2412ce1d2225d6e
Thanks @ksuquix !
