### ISSUE TITLE
docker-compose configuration update for self-signed certificate

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment-live#25]
# What?
`docker-compose-selfsigned.yml` needs some edits in its drive mappings for the esmero-web container. Currently the alternate nginx.conf and generated cert locations are not picked up by the container.

**Comment by DiegoPino** [comment]
@ksuquix this solves the self-cert issue you reported. My bad, I was stuck with the idea of the other two Certbot based containers that use a different mechanic. This one could also use a template to be honest but I feel in the long term we won't be using self cert a lot.
