### ISSUE TITLE
Make redis max memory configurable

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment-live#76]
# What?
The redis container currently ships with maxmemory default and should be configurable via (e.g.) `--maxmemory 3gb` in the docker-compose command flags or in the conf file.

@DiegoPino should we maybe mount redis.conf and allow for fine-tuning?

**Comment by DiegoPino** [comment]
Also, we need to set the max memory policy
and we need to make sure that if max memory is SET, then queues can not go into cache
at least not Persistent queues

**Comment by DiegoPino** [comment]
@aksm I prefer we add all commands inline instead of a redis.conf?

**Comment by aksm** [comment]
@DiegoPino makes sense. Was thinking the same but considering advanced use cases. Maybe just document redis.conf setup for those that want to go that route.

**Comment by aksm** [comment]
Resolved via 924be4d503e8a23a249def08fee69a5d5dd6aa75 and 121bfc83f8f904809d8d95580c7b6e646e33b26d.
