### ISSUE TITLE
Export/import metadata Displays script using JSON API and JQ

### ISSUE THREAD

**Issue by DiegoPino** [esmero/archipelago-deployment-live#81]
# What?

Using the JSON:API, `jq` and some bash/sh tooling we need to build one scripts that can
1.- Export all Metadata Displays from JSON:API, clean, remove fixed fields and create one file per metadata display
2.- Generates a reingest script (similar to our `update_deployed.sh`) that can be used then to ingest somewhere else those metadata entities.

 I started working and based on my simple proto-idea @aksm provided this

```Shell
curl -w "\n" --user jsonapi:****** -H 'Accept: application/vnd.api+json' \
-H 'Content-type: application/vnd.api+json' \ 
-XGET 'http://localhost:8001/jsonapi/metadatadisplay_entity/metadatadisplay_entity' \
 | jq -cr '.data[]|del(.relationships)|del(.attributes.created)|del(.attributes.drupal_internal__id)|del(.attributes.changed)|del(.attributes.link)| \{"data": .}'| awk -F'\t' '{ i++ ; fname = "metadatadisplay_entity_" i ".json"; print > fname; close(fname)}'
```

**Comment by DiegoPino** [comment]
Tiny Note: each output file needs to match the format of https://github.com/esmero/archipelago-deployment-live/blob/1.0.0/drupal/d8content/metadatadisplay_entity_01.json

**Comment by aksm** [comment]
`if [[ -v "${ARCHIPELAGO_DOMAIN}" ]];` doesn't work on Mac so switch to `if [ -n "${ARCHIPELAGO_DOMAIN}" ];`.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/archipelago-deployment-live/commit/9f5b3a5b8b0dd953744ff46bf4efb005fea606c7
