### ISSUE TITLE
Export/import script should delete existing displays in folder first

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment-live#92]
# What?
The metadatadisplay entity import/export script currently downloads to the specified folder without deleting what's already there. It would be better to delete any existing JSON files before exporting so as to avoid unintentionally importing old, leftover files. We can additionally provide a flag for exporting without deleting.

@DiegoPino I believe you had mentioned this at one point, and I had forgotten about until now while writing documentation for this.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/archipelago-deployment-live/commit/eb9426e5864c82f127c16894b279a222fb042fd0

Thanks @aksm !
