### ISSUE TITLE
Set PHP display_startup_errors to off

### ISSUE THREAD

**Issue by aksm** [esmero/archipelago-deployment-live#99]
# What?
While `display_errors` is defaulted to off, `display_startup_errors` is set to on (by default?). This means when a production instance fails, it still sends a 200. As recommended in the [PHP docs](https://www.php.net/manual/en/errorfunc.configuration.php#ini.display-startup-errors), it should be set to off for archipelago-deployment-live.

**Comment by DiegoPino** [comment]
Good one!

**Comment by aksm** [comment]
After some testing, it appears that the defaults for both of the above settings changed as of PHP 8 ([see here](https://www.php.net/manual/en/errorfunc.configuration.php)). Both need to be explicitly set to off. Maybe explicitly setting all of the other supposed default settings is not a bad idea for stability?

**Comment by DiegoPino** [comment]
@aksm I would not touch defaults (except the one(s) mention In this issue). These might change/be renamed and also makes me feel we would need to document those too?

**Comment by aksm** [comment]
Resolved by f0b98684a7fe85928590629613af83a643072a99.
